### ISSUE TITLE
data-game-url seems borked

### ISSUE THREAD

**Issue by bobthemighty** [adamreisnz/seki#1]
I'm trying to use Seki to build a talk on Go for work, so I'm embedding it in  Marp presentation. So far, so good!

I've been unable to use the data-game-url attr, though. I have an sgf with the following content at `sgf/liberties.sgf`

```
(;GM[1]FF[4]CA[UTF-8]AP[Sabaki:0.52.2]KM[6.5]SZ[9]DT[2024-01-25];B[ee]PL[B];B[ee]PL[B]LB[de:4][ed:1][ef:3][fe:2])
```

and a board like so

```
        <div
          class="seki-board-dynamic fixed-size square"
          data-game-url="/sgf/liberties.sgf"></div>

```

When the sgf loads, the `regexSgf` match is mangling the response, so I get a bad format error.

**Comment by adamreisnz** [comment]
Thanks for reporting! Fixed in 1.8.11
Please let me know if you run into any other issues.
