### ISSUE TITLE
Feature request, Estimate & Editor toggle. + 1 bug

### ISSUE THREAD

**Issue by ghost** [adamreisnz/seki#4]
## Bug

In letsplaygo if we open any pro game record in editor and we do any editing on the board, then the game tree is distorted, like it won't show us any move from actual game after the point where we play a stone.
It happens for any game we open after that.
So if I open in editor game1, and play 1 move. Then even if we open a 2nd and 3rd game it still shows the game record we edited.

## Thank you for this project I found this out by accident and really loved it.

**Comment by adamreisnz** [comment]
Hi @B-and-B-Studio , thank you for the comments and feedback.

The editor in Let's Play Go actually has an estimator built in, you can access it here:
![image](https://github.com/user-attachments/assets/d5515d1c-dffd-4420-9ac7-2cf90ea9d6a7)

This is something that is beyond the scope of the Seki player itself though, so it can only be found in Let's Play Go.
Will see if this can be added to the games viewer/replayer at some stage as well.

I'll have a look into the bug that you encountered. 

Glad you like the project!

**Comment by ghost** [comment]
That's great 😃 
Thank you for your efforts 🙏🏻

**Comment by adamreisnz** [comment]
The reported bug with pro games incorrectly loading into the editor should be fixed now
