### ISSUE TITLE
about SabakiHQ/deadstones

### ISSUE THREAD

**Issue by kanitabe** [adamreisnz/seki#5]
Hello adamreisnz,
Forgive my question in a directly unrelated repository.

Thanks for updating the neglected SabakiHQ/deadstones project!
I believe deadstones is a valuable program that supports the foundation of a highly portable Go program that can be used in other Go projects.
And this seki project is great too! I want to use this someday.

I tried writing the code based on your pull request, but I encountered an error when loading the wasm.

Is there anything I might be doing wrong?

the deadstones_bg.wasm I am using is the one obtained by installing the original SabakiHQ/deadstones via npm (I deleted it and am now using the version from your forked project).

<img width="785" alt="2024-09-22_00h43_56" src="https://github.com/user-attachments/assets/70431b01-4ec1-44d1-b609-3e2cdcb95556">

**Comment by adamreisnz** [comment]
Hi, I can't really help debug this for you as this is not my library, but I'll share some code of how I've used it and how it worked correctly for me:

```js
import {guess, getProbabilityMap as probMap, useFetch} from '@sabaki/deadstones'
import wasm from '@/assets/wasm/deadstones_bg.wasm?url'

//Use fetch
useFetch(wasm)

/**
 * Dead stones composable
 */
export function useDeadStones() {

  //Guess dead stones
  const guessDeadStones = (matrix, finished = false) => {
    return guess(matrix, {
      finished,
      iterations: 100,
    })
  }

  //Get probability map
  const getProbabilityMap = (matrix) => {
    return probMap(matrix, 100)
  }

  //Expose interface
  return {
    guessDeadStones,
    getProbabilityMap,
  }
}
```

Not sure if it makes a different, but I'm building this project with Vite.
I think you need to make sure that you have some kind of replacement for `fs` as that is normally not available in the browser.

And in `package.json` I'm just using my fork: 

```
"@sabaki/deadstones": "git+https://github.com/adamreisnz/deadstones.git",
```

**Comment by kanitabe** [comment]
Thank you very much. The wasm ran successfully.
For the benefit of others, I will leave the code that worked.
The execution environment is Vite, the wasm used is the pre-built one, and @sabaki/deadstones is the forked version.


src
├── assets
│   ├── deadstones_bg.wasm
│   └── react.svg
├── App.css
├── App.tsx
├── deadstones.tsx
├── index.css
├── main.tsx
└── vite-env.d.ts

package.json
```package.json
  "dependencies": {
    "@sabaki/deadstones": "github:adamreisnz/deadstones",
    "react": "^18.3.1",
    "react-dom": "^18.3.1"
  },
```

App.tsx
```App.tsx
import { useEffect, useState } from 'react'
import './App.css'
import useDeadStones from './deadstones';

function App() {
  const { guessDeadStones, getProbabilityMap } = useDeadStones();

  useEffect(() => {
    const fetchDeadstones = async () => {
      const board = [
        [ 0,  0,  1,  0, -1, -1,  1,  0, 0],
        [ 1,  0,  1, -1, -1,  1,  1,  1, 0],
        [ 0,  0,  1, -1,  0,  1, -1, -1, 0],
        [ 1,  1,  1, -1, -1, -1,  1, -1, 0],
        [ 1, -1,  1,  1, -1,  1,  1,  1, 0],
        [-1, -1, -1, -1, -1,  1,  0,  0, 0],
        [ 0, -1, -1,  0, -1,  1,  1,  1, 1],
        [ 0,  0,  0,  0,  0, -1, -1, -1, 1],
        [ 0,  0,  0,  0,  0,  0,  0, -1, 0]
      ];

      const result = await guessDeadStones(board);
      const result2 = await getProbabilityMap(board);
      console.log(result);
      console.log(result2);
    };

    fetchDeadstones();
  }, []);

  return (
    <>
    </>
  )
}

export default App
```

deadstones.tsx
```deadstones.tsx
import {guess, getProbabilityMap as probMap, useFetch} from '@sabaki/deadstones'
import wasm from './assets/deadstones_bg.wasm?url'

/**
 * Dead stones composable
 */
export default function useDeadStones() {

  // Use fetch
  useFetch(wasm)

  //Guess dead stones
  const guessDeadStones = async (matrix, finished = false) => {
    return guess(matrix, {
      finished,
      iterations: 100,
    })
  }

  //Get probability map
  const getProbabilityMap = async (matrix) => {
    return probMap(matrix, 100)
  }

  //Expose interface
  return {
    guessDeadStones,
    getProbabilityMap,
  }
}
```

**Comment by adamreisnz** [comment]
Great, thanks!
